### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by Balimaar** [MerlinCooper/iRacingReplayDirector#45]
both links provided in the readme give me an access denied warning and I have no idea how to compile. when you have time could you fix the links or maybe have a guide up on how to compile the build?

cheers much appreciate your work <3 I've been searching for a replacement for the replay director for ages!

**Comment by MerlinCooper** [comment]
Due to Vipoo not longer being active the links for downloading and updating no longer working. The readme therefore is misleading although I added a remark that it is not up to date - will have a look at it and update the readme soon.

If you want to use the ReplayDirector right away you either can download an older version provided on the iRacing website ([link](url)https://members.iracing.com/jforum/posts/list/3638321.page) or download the sources and compile them. Currently working on a CD solution to make that easier for the future.

**Comment by MerlinCooper** [comment]
@Balimaar 

Did my reply solve the issue - or are still questions open?

**Comment by MerlinCooper** [comment]
Most recent binaries are attached to the corresponding release.
https://github.com/MerlinCooper/iRacingReplayDirector/releases/latest
