### ISSUE TITLE
Is it possible to include updated modern overlays?

### ISSUE THREAD

**Issue by mrzoops** [MerlinCooper/iRacingReplayDirector#68]
How intensive would it be to create newer modern looking overlays? How are the overlays designed? I may be able to design something that could be integrated but now sure how they are created.

**Comment by MerlinCooper** [comment]
The current overlays are implemented as c# plugins. Thus for every design change you would have to change part of the code. When I started using the tool there where two versions so the plug-in available. Because I didn‘t like the design either and and where using third party software I
 Just added the No-overlay option. Which allows you to use other overlays.

With regard to the effort I would say it‘s huge to implement a good and flexible overlay. Beside the drawing to the screen you would need some kind of editor. There are good overlay tools available and I would suggest to use them. What might be on option though is trying to remotely control such an overlay to e.g. enable re-plays, slow-motions, switch of scenes controlled by the application

**Comment by mrzoops** [comment]
Thank you for the explanation and suggestion!
